/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Phonetic
 #	author : miyako
 #	2016/06/21
 #
 # --------------------------------------------------------------------------------*/

#if VERSIONWIN
#include <initguid.H>
#include <msctf.h>
#include <msaatext.h>
#include <ctffunc.h>
#include <stdio.h>
#include "TsfReconverter.h"
#else
#include <ApplicationServices/ApplicationServices.h>
#endif

// --- Phonetic
void PHONETIC(sLONG_PTR *pResult, PackagePtr pParams);
